// Code generated by "stringer -type=Level"; DO NOT EDIT.

package ezlog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Disabled - -1]
	_ = x[EmergLevel-0]
	_ = x[AlertLevel-1]
	_ = x[CritLevel-2]
	_ = x[ErrLevel-3]
	_ = x[WarningLevel-4]
	_ = x[NoticeLevel-5]
	_ = x[InfoLevel-6]
	_ = x[DebugLevel-7]
	_ = x[TraceLevel-8]
}

const _Level_name = "DisabledEmergLevelAlertLevelCritLevelErrLevelWarningLevelNoticeLevelInfoLevelDebugLevelTraceLevel"

var _Level_index = [...]uint8{0, 8, 18, 28, 37, 45, 57, 68, 77, 87, 97}

func (i Level) String() string {
	i -= -1
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
